import { AIAgent, Task, Document, Notification, Report, ActivityLog, Client, Case, DashboardMetrics } from '@/types'

export const mockAgents: AIAgent[] = [
  {
    id: 'agent-1',
    name: 'Lexi - Legal Analyst',
    type: 'legal',
    status: 'active',
    description: 'Specialized in contract analysis, legal research, and compliance checking. Trained on Indonesian corporate law, international arbitration, and regulatory frameworks.',
    capabilities: ['Contract Analysis', 'Legal Research', 'Compliance Check', 'Risk Assessment', 'Document Review'],
    lastActive: new Date(Date.now() - 2 * 60000).toISOString(),
    tasksCompleted: 1247,
    accuracy: 97.3,
    responseTime: 1.2,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o',
      temperature: 0.3,
      maxTokens: 4096,
      systemPrompt: 'You are an expert legal analyst specializing in corporate law, contract review, and regulatory compliance. Provide thorough, accurate analysis with citations.',
      tools: ['document_parser', 'legal_search', 'citation_finder'],
      autoExecute: false,
      approvalRequired: true,
    },
    metrics: {
      totalRequests: 3421,
      avgResponseTime: 1.2,
      successRate: 97.3,
      tokensUsed: 2840000,
      costEstimate: 142.50,
      uptime: 99.8,
    },
  },
  {
    id: 'agent-2',
    name: 'Research - Intelligence Agent',
    type: 'research',
    status: 'active',
    description: 'Deep research capabilities across legal databases, case law, regulatory updates, and market intelligence. Integrates with multiple legal information sources.',
    capabilities: ['Case Law Search', 'Regulatory Tracking', 'Market Research', 'Competitive Analysis', 'Precedent Analysis'],
    lastActive: new Date(Date.now() - 5 * 60000).toISOString(),
    tasksCompleted: 892,
    accuracy: 94.8,
    responseTime: 2.8,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o',
      temperature: 0.5,
      maxTokens: 8192,
      systemPrompt: 'You are a research intelligence agent with access to comprehensive legal databases. Provide detailed research with sources and methodology.',
      tools: ['web_search', 'legal_db', 'news_api', 'analytics'],
      autoExecute: true,
      approvalRequired: false,
    },
    metrics: {
      totalRequests: 2156,
      avgResponseTime: 2.8,
      successRate: 94.8,
      tokensUsed: 4200000,
      costEstimate: 210.00,
      uptime: 99.5,
    },
  },
  {
    id: 'agent-3',
    name: 'TechGuard - IT Security Agent',
    type: 'it',
    status: 'active',
    description: 'Cybersecurity and IT compliance specialist. Monitors security posture, analyzes vulnerabilities, and ensures regulatory compliance for data protection.',
    capabilities: ['Security Audit', 'Vulnerability Scan', 'Compliance Check', 'Incident Response', 'Policy Review'],
    lastActive: new Date(Date.now() - 1 * 60000).toISOString(),
    tasksCompleted: 534,
    accuracy: 98.1,
    responseTime: 0.8,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o-mini',
      temperature: 0.2,
      maxTokens: 2048,
      systemPrompt: 'You are an IT security and compliance specialist. Analyze security configurations, identify vulnerabilities, and provide actionable remediation steps.',
      tools: ['security_scanner', 'compliance_checker', 'policy_analyzer'],
      autoExecute: true,
      approvalRequired: false,
    },
    metrics: {
      totalRequests: 1876,
      avgResponseTime: 0.8,
      successRate: 98.1,
      tokensUsed: 980000,
      costEstimate: 49.00,
      uptime: 99.9,
    },
  },
  {
    id: 'agent-4',
    name: 'Exec - Executive Summary',
    type: 'executive',
    status: 'idle',
    description: 'Generates executive summaries, strategic insights, and board-ready reports from complex legal and business data.',
    capabilities: ['Executive Summary', 'Strategic Analysis', 'Board Reports', 'Risk Dashboard', 'KPI Tracking'],
    lastActive: new Date(Date.now() - 45 * 60000).toISOString(),
    tasksCompleted: 321,
    accuracy: 96.5,
    responseTime: 3.5,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o',
      temperature: 0.4,
      maxTokens: 4096,
      systemPrompt: 'You are an executive assistant AI. Synthesize complex information into clear, actionable executive summaries and strategic recommendations.',
      tools: ['data_analyzer', 'report_generator', 'chart_maker'],
      autoExecute: false,
      approvalRequired: true,
    },
    metrics: {
      totalRequests: 678,
      avgResponseTime: 3.5,
      successRate: 96.5,
      tokensUsed: 1560000,
      costEstimate: 78.00,
      uptime: 98.2,
    },
  },
  {
    id: 'agent-5',
    name: 'Compliance - RegWatch',
    type: 'compliance',
    status: 'active',
    description: 'Regulatory compliance monitoring agent. Tracks changes in laws, regulations, and standards across multiple jurisdictions.',
    capabilities: ['Regulatory Tracking', 'Compliance Mapping', 'Gap Analysis', 'Audit Prep', 'Policy Update'],
    lastActive: new Date(Date.now() - 8 * 60000).toISOString(),
    tasksCompleted: 756,
    accuracy: 95.2,
    responseTime: 1.5,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o',
      temperature: 0.3,
      maxTokens: 4096,
      systemPrompt: 'You are a regulatory compliance specialist. Monitor regulatory changes, assess compliance gaps, and provide actionable recommendations.',
      tools: ['reg_db', 'compliance_mapper', 'gap_analyzer'],
      autoExecute: true,
      approvalRequired: false,
    },
    metrics: {
      totalRequests: 1890,
      avgResponseTime: 1.5,
      successRate: 95.2,
      tokensUsed: 2100000,
      costEstimate: 105.00,
      uptime: 99.6,
    },
  },
  {
    id: 'agent-6',
    name: 'Custom - ContractBot',
    type: 'custom',
    status: 'offline',
    description: 'Custom-trained agent for specific contract types and client requirements. Currently offline for maintenance.',
    capabilities: ['NDA Review', 'Service Agreement', 'Employment Contract', 'Licensing Agreement'],
    lastActive: new Date(Date.now() - 360 * 60000).toISOString(),
    tasksCompleted: 445,
    accuracy: 93.7,
    responseTime: 2.1,
    tenantId: 'tenant-1',
    config: {
      model: 'gpt-4o',
      temperature: 0.3,
      maxTokens: 4096,
      systemPrompt: 'Custom contract analysis agent. Specialized in specific contract types and client templates.',
      tools: ['contract_parser', 'template_matcher'],
      autoExecute: false,
      approvalRequired: true,
    },
    metrics: {
      totalRequests: 1123,
      avgResponseTime: 2.1,
      successRate: 93.7,
      tokensUsed: 1340000,
      costEstimate: 67.00,
      uptime: 95.4,
    },
  },
]

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Contract Review: PT Maju Jaya Acquisition',
    description: 'Review and analyze acquisition agreement for PT Maju Jaya. Identify key risk clauses, regulatory compliance issues, and recommend amendments.',
    status: 'running',
    priority: 'critical',
    agentId: 'agent-1',
    agentName: 'Lexi - Legal Analyst',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Regulatory Update Analysis: OJK Circular 2024/15',
    description: 'Analyze the new OJK circular regarding digital asset custody. Assess impact on current client portfolios and compliance requirements.',
    status: 'completed',
    priority: 'high',
    agentId: 'agent-5',
    agentName: 'Compliance - RegWatch',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 115 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    duration: 1500,
    result: 'Analysis complete. 3 high-priority compliance gaps identified. 12 recommendations generated. Full report available.',
  },
  {
    id: 'task-3',
    title: 'Security Audit: Client Portal Infrastructure',
    description: 'Comprehensive security audit of client portal infrastructure. Check for vulnerabilities, misconfigurations, and compliance with ISO 27001.',
    status: 'running',
    priority: 'high',
    agentId: 'agent-3',
    agentName: 'TechGuard - IT Security Agent',
    tenantId: 'tenant-1',
    createdBy: 'user-2',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Executive Summary: Q4 Legal Operations',
    description: 'Generate executive summary for Q4 legal operations including case outcomes, cost analysis, and strategic recommendations.',
    status: 'pending',
    priority: 'medium',
    agentId: 'agent-4',
    agentName: 'Exec - Executive Summary',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'task-5',
    title: 'Case Law Research: Precedent for IP Dispute',
    description: 'Research relevant case law and precedents for ongoing intellectual property dispute. Focus on software patent infringement cases in SEA region.',
    status: 'completed',
    priority: 'high',
    agentId: 'agent-2',
    agentName: 'Research - Intelligence Agent',
    tenantId: 'tenant-1',
    createdBy: 'user-3',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 175 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 140 * 60000).toISOString(),
    duration: 2100,
    result: 'Found 23 relevant precedents. 7 strongly supporting client position. Detailed memo with citations generated.',
  },
  {
    id: 'task-6',
    title: 'NDA Review: Partnership with TechVentures',
    description: 'Review non-disclosure agreement for potential partnership with TechVentures Inc. Check for mutual obligations, survival clauses, and jurisdictional issues.',
    status: 'completed',
    priority: 'medium',
    agentId: 'agent-1',
    agentName: 'Lexi - Legal Analyst',
    tenantId: 'tenant-1',
    createdBy: 'user-2',
    createdAt: new Date(Date.now() - 240 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 235 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 220 * 60000).toISOString(),
    duration: 900,
    result: 'NDA reviewed. 4 recommended amendments identified. No critical red flags. Ready for partner legal review.',
  },
  {
    id: 'task-7',
    title: 'GDPR Compliance Assessment: Data Processing',
    description: 'Assess GDPR compliance for new data processing activities. Review consent mechanisms, data retention policies, and cross-border transfer safeguards.',
    status: 'failed',
    priority: 'critical',
    agentId: 'agent-5',
    agentName: 'Compliance - RegWatch',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 300 * 60000).toISOString(),
    startedAt: new Date(Date.now() - 295 * 60000).toISOString(),
    completedAt: new Date(Date.now() - 280 * 60000).toISOString(),
    duration: 900,
    error: 'Insufficient data provided for processing activity assessment. Missing data flow diagrams and third-party processor agreements.',
  },
]

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'Acquisition_Agreement_PT_Maju_Jaya_v2.pdf',
    type: 'application/pdf',
    size: 2840000,
    status: 'completed',
    tenantId: 'tenant-1',
    uploadedBy: 'user-1',
    uploadedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    processedAt: new Date(Date.now() - 47 * 3600000).toISOString(),
    summary: 'Acquisition agreement between PT Maju Jaya and PT Sejahtera. 47 pages. Key clauses: purchase price adjustment, representations and warranties, indemnification provisions.',
    tags: ['acquisition', 'corporate', 'indonesia', 'high-priority'],
    folder: 'M&A',
  },
  {
    id: 'doc-2',
    name: 'OJK_Circular_2024_15_Analysis.docx',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 1250000,
    status: 'completed',
    tenantId: 'tenant-1',
    uploadedBy: 'user-2',
    uploadedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    processedAt: new Date(Date.now() - 71 * 3600000).toISOString(),
    summary: 'Regulatory analysis of OJK Circular 2024/15 regarding digital asset custody services. Impact assessment for 12 client portfolios.',
    tags: ['regulatory', 'ojk', 'digital-assets', 'compliance'],
    folder: 'Regulatory',
  },
  {
    id: 'doc-3',
    name: 'Security_Audit_Report_Q4_2024.pdf',
    type: 'application/pdf',
    size: 5600000,
    status: 'processing',
    tenantId: 'tenant-1',
    uploadedBy: 'user-3',
    uploadedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    tags: ['security', 'audit', 'iso27001'],
    folder: 'IT Security',
  },
  {
    id: 'doc-4',
    name: 'Employment_Contract_Template_2024.docx',
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    size: 890000,
    status: 'completed',
    tenantId: 'tenant-1',
    uploadedBy: 'user-1',
    uploadedAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    processedAt: new Date(Date.now() - 119 * 3600000).toISOString(),
    summary: 'Standard employment contract template updated for 2024. Compliant with latest labor law amendments. Includes remote work clauses.',
    tags: ['hr', 'employment', 'template', 'indonesia'],
    folder: 'HR & Employment',
  },
  {
    id: 'doc-5',
    name: 'IP_Portfolio_Assessment.xlsx',
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    size: 2100000,
    status: 'completed',
    tenantId: 'tenant-1',
    uploadedBy: 'user-2',
    uploadedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    processedAt: new Date(Date.now() - 95 * 3600000).toISOString(),
    summary: 'Intellectual property portfolio assessment for TechCorp Indonesia. 47 patents, 12 trademarks, 8 copyrights evaluated.',
    tags: ['ip', 'patents', 'assessment', 'techcorp'],
    folder: 'IP & Patents',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'Task Completed: Regulatory Update Analysis',
    message: 'Compliance agent has completed the OJK Circular 2024/15 analysis. 3 high-priority gaps identified.',
    type: 'success',
    read: false,
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    link: '/tasks/task-2',
    tenantId: 'tenant-1',
  },
  {
    id: 'notif-2',
    title: 'New Document Uploaded',
    message: 'Security audit report Q4 2024 has been uploaded and is being processed.',
    type: 'info',
    read: false,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    link: '/documents/doc-3',
    tenantId: 'tenant-1',
  },
  {
    id: 'notif-3',
    title: 'Task Failed: GDPR Compliance Assessment',
    message: 'Compliance agent failed to complete GDPR assessment due to insufficient data. Action required.',
    type: 'error',
    read: false,
    createdAt: new Date(Date.now() - 280 * 60000).toISOString(),
    link: '/tasks/task-7',
    tenantId: 'tenant-1',
  },
  {
    id: 'notif-4',
    title: 'Agent Alert: Lexi - High Load Detected',
    message: 'Legal Analyst agent is experiencing high request load. Response times may be slightly elevated.',
    type: 'warning',
    read: true,
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    tenantId: 'tenant-1',
  },
  {
    id: 'notif-5',
    title: 'Weekly Executive Summary Ready',
    message: 'Your weekly executive summary for legal operations is now available.',
    type: 'info',
    read: true,
    createdAt: new Date(Date.now() - 1440 * 60000).toISOString(),
    link: '/reports',
    tenantId: 'tenant-1',
  },
]

export const mockReports: Report[] = [
  {
    id: 'report-1',
    title: 'Q4 2024 Legal Operations Executive Summary',
    type: 'executive',
    status: 'completed',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 168 * 3600000).toISOString(),
    completedAt: new Date(Date.now() - 167 * 3600000).toISOString(),
    summary: 'Comprehensive overview of Q4 legal operations including 47 completed cases, $2.3M in recovered value, and 98% client satisfaction rate.',
    metrics: {
      casesCompleted: 47,
      valueRecovered: 2300000,
      clientSatisfaction: 98,
      avgResolutionTime: 12.5,
      complianceScore: 96,
    },
    aiGenerated: true,
  },
  {
    id: 'report-2',
    title: 'Regulatory Compliance Gap Analysis',
    type: 'compliance',
    status: 'completed',
    tenantId: 'tenant-1',
    createdBy: 'user-2',
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    completedAt: new Date(Date.now() - 70 * 3600000).toISOString(),
    summary: 'Identified 8 compliance gaps across 3 regulatory frameworks. 5 critical, 3 medium priority. Remediation roadmap provided.',
    metrics: {
      totalGaps: 8,
      criticalGaps: 5,
      mediumGaps: 3,
      remediationCost: 45000,
      timeline: 90,
    },
    aiGenerated: true,
  },
  {
    id: 'report-3',
    title: 'AI Agent Performance Review - November 2024',
    type: 'performance',
    status: 'completed',
    tenantId: 'tenant-1',
    createdBy: 'user-1',
    createdAt: new Date(Date.now() - 240 * 3600000).toISOString(),
    completedAt: new Date(Date.now() - 239 * 3600000).toISOString(),
    summary: 'Monthly performance review of all active AI agents. Average accuracy: 96.2%, uptime: 99.4%, cost efficiency improved by 12%.',
    metrics: {
      avgAccuracy: 96.2,
      avgUptime: 99.4,
      totalTasks: 1567,
      costEfficiency: 12,
      userSatisfaction: 94,
    },
    aiGenerated: true,
  },
]

export const mockActivityLogs: ActivityLog[] = [
  {
    id: 'log-1',
    action: 'Task Created',
    entityType: 'task',
    entityId: 'task-1',
    entityName: 'Contract Review: PT Maju Jaya Acquisition',
    userId: 'user-1',
    userName: 'Sarah Chen',
    tenantId: 'tenant-1',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    severity: 'info',
  },
  {
    id: 'log-2',
    action: 'Agent Activated',
    entityType: 'agent',
    entityId: 'agent-3',
    entityName: 'TechGuard - IT Security Agent',
    userId: 'system',
    userName: 'System',
    tenantId: 'tenant-1',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    severity: 'info',
  },
  {
    id: 'log-3',
    action: 'Document Uploaded',
    entityType: 'document',
    entityId: 'doc-3',
    entityName: 'Security_Audit_Report_Q4_2024.pdf',
    userId: 'user-3',
    userName: 'Michael Park',
    tenantId: 'tenant-1',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    severity: 'info',
  },
  {
    id: 'log-4',
    action: 'Task Failed',
    entityType: 'task',
    entityId: 'task-7',
    entityName: 'GDPR Compliance Assessment',
    userId: 'agent-5',
    userName: 'Compliance - RegWatch',
    tenantId: 'tenant-1',
    timestamp: new Date(Date.now() - 280 * 60000).toISOString(),
    severity: 'error',
    details: { error: 'Insufficient data for assessment' },
  },
  {
    id: 'log-5',
    action: 'Report Generated',
    entityType: 'report',
    entityId: 'report-1',
    entityName: 'Q4 2024 Legal Operations Executive Summary',
    userId: 'user-1',
    userName: 'Sarah Chen',
    tenantId: 'tenant-1',
    timestamp: new Date(Date.now() - 168 * 3600000).toISOString(),
    severity: 'info',
  },
]

export const mockClients: Client[] = [
  {
    id: 'client-1',
    name: 'PT Maju Jaya Indonesia',
    email: 'legal@majujaya.co.id',
    company: 'PT Maju Jaya Indonesia',
    industry: 'Manufacturing',
    status: 'active',
    tenantId: 'tenant-1',
    assignedConsultant: 'user-1',
    totalCases: 12,
    openCases: 3,
    lastContact: new Date(Date.now() - 2 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 86400000).toISOString(),
    notes: 'Major client since 2023. Focus on M&A and corporate restructuring.',
  },
  {
    id: 'client-2',
    name: 'TechVentures Pte Ltd',
    email: 'general@techventures.sg',
    company: 'TechVentures Pte Ltd',
    industry: 'Technology',
    status: 'active',
    tenantId: 'tenant-1',
    assignedConsultant: 'user-2',
    totalCases: 8,
    openCases: 2,
    lastContact: new Date(Date.now() - 24 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 120 * 86400000).toISOString(),
    notes: 'Singapore-based tech startup. IP protection and data privacy focus.',
  },
  {
    id: 'client-3',
    name: 'Global Finance Corp',
    email: 'compliance@globalfinance.com',
    company: 'Global Finance Corp',
    industry: 'Financial Services',
    status: 'active',
    tenantId: 'tenant-1',
    assignedConsultant: 'user-3',
    totalCases: 15,
    openCases: 5,
    lastContact: new Date(Date.now() - 6 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    notes: 'Multi-jurisdictional compliance and regulatory advisory.',
  },
  {
    id: 'client-4',
    name: 'GreenEnergy Solutions',
    email: 'legal@greenenergy.id',
    company: 'GreenEnergy Solutions',
    industry: 'Energy',
    status: 'pending',
    tenantId: 'tenant-1',
    assignedConsultant: 'user-1',
    totalCases: 2,
    openCases: 2,
    lastContact: new Date(Date.now() - 48 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    notes: 'New client. Renewable energy project financing and ESG compliance.',
  },
]

export const mockCases: Case[] = [
  {
    id: 'case-1',
    title: 'PT Maju Jaya - Acquisition Due Diligence',
    description: 'Comprehensive legal due diligence for the acquisition of PT Sejahtera by PT Maju Jaya.',
    status: 'in_progress',
    priority: 'critical',
    type: 'legal',
    clientId: 'client-1',
    clientName: 'PT Maju Jaya Indonesia',
    tenantId: 'tenant-1',
    assignedTo: 'user-1',
    assignedAgent: 'agent-1',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    dueDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    documents: ['doc-1'],
    tasks: ['task-1'],
    notes: 'Key milestone: Contract review in progress. Regulatory approval pending.',
  },
  {
    id: 'case-2',
    title: 'TechVentures - IP Infringement Defense',
    description: 'Defense against patent infringement claim in Singapore High Court.',
    status: 'in_progress',
    priority: 'high',
    type: 'legal',
    clientId: 'client-2',
    clientName: 'TechVentures Pte Ltd',
    tenantId: 'tenant-1',
    assignedTo: 'user-2',
    assignedAgent: 'agent-2',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    dueDate: new Date(Date.now() + 45 * 86400000).toISOString(),
    documents: ['doc-5'],
    tasks: ['task-5'],
    notes: 'Precedent research completed. Preparing defense strategy.',
  },
  {
    id: 'case-3',
    title: 'Global Finance - OJK Compliance Review',
    description: 'Comprehensive compliance review following new OJK regulations.',
    status: 'open',
    priority: 'critical',
    type: 'compliance',
    clientId: 'client-3',
    clientName: 'Global Finance Corp',
    tenantId: 'tenant-1',
    assignedTo: 'user-3',
    assignedAgent: 'agent-5',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    dueDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    documents: ['doc-2'],
    tasks: ['task-2'],
    notes: 'Regulatory analysis complete. Gap assessment in progress.',
  },
]

export const mockDashboardMetrics: DashboardMetrics = {
  totalAgents: 6,
  activeAgents: 4,
  totalTasks: 1567,
  completedTasks: 1243,
  pendingTasks: 89,
  totalDocuments: 342,
  processedDocuments: 298,
  avgResponseTime: 1.8,
  systemUptime: 99.7,
  tokenUsage: 12840000,
  costEstimate: 642.00,
  tasksByAgent: [
    { agentId: 'agent-1', agentName: 'Lexi', count: 342 },
    { agentId: 'agent-2', agentName: 'Research', count: 256 },
    { agentId: 'agent-3', agentName: 'TechGuard', count: 198 },
    { agentId: 'agent-5', agentName: 'Compliance', count: 267 },
    { agentId: 'agent-4', agentName: 'Exec', count: 89 },
    { agentId: 'agent-6', agentName: 'ContractBot', count: 91 },
  ],
  tasksByStatus: [
    { status: 'completed', count: 1243 },
    { status: 'running', count: 45 },
    { status: 'pending', count: 89 },
    { status: 'failed', count: 23 },
    { status: 'cancelled', count: 167 },
  ],
  tasksOverTime: [
    { date: '2024-10-01', count: 45 },
    { date: '2024-10-08', count: 52 },
    { date: '2024-10-15', count: 38 },
    { date: '2024-10-22', count: 61 },
    { date: '2024-10-29', count: 55 },
    { date: '2024-11-05', count: 48 },
    { date: '2024-11-12', count: 67 },
    { date: '2024-11-19', count: 72 },
    { date: '2024-11-26', count: 58 },
    { date: '2024-12-03', count: 64 },
    { date: '2024-12-10', count: 71 },
    { date: '2024-12-17', count: 59 },
  ],
  agentPerformance: [
    { agentId: 'agent-1', agentName: 'Lexi', accuracy: 97.3, speed: 1.2, load: 78 },
    { agentId: 'agent-2', agentName: 'Research', accuracy: 94.8, speed: 2.8, load: 65 },
    { agentId: 'agent-3', agentName: 'TechGuard', accuracy: 98.1, speed: 0.8, load: 45 },
    { agentId: 'agent-5', agentName: 'Compliance', accuracy: 95.2, speed: 1.5, load: 72 },
    { agentId: 'agent-4', agentName: 'Exec', accuracy: 96.5, speed: 3.5, load: 34 },
    { agentId: 'agent-6', agentName: 'ContractBot', accuracy: 93.7, speed: 2.1, load: 0 },
  ],
}
